#!/usr/bin/env python3
"""
Hermes Runtime Initialization Script

Initializes the runtime environment with:
- Health checks (pre-flight validation)
- Persistent volume mounts verification
- Memory preload
- Session resurrection
- Agent identity restoration
- Gateway daemon startup

Flags:
  --doctor     Run health checks and exit (0=healthy, 1=issues)
  --fix        Auto-fix issues found during health checks
  --setup      Non-interactive setup from OpenClaw config or environment
  --quick      Quick health check (paths, env, imports only)
"""

import argparse
import asyncio
import json
import logging
import os
import signal
import sys
from pathlib import Path
from datetime import datetime

logger = logging.getLogger(__name__)


def run_health_checks(quick: bool = False, fix: bool = False,
                      categories: list = None, json_output: bool = False) -> int:
    """Run health checks via doctor bridge and return exit code."""
    try:
        health_dir = Path(__file__).resolve().parent.parent.parent.parent / "health"
        if health_dir.exists():
            sys.path.insert(0, str(health_dir.parent))
            from health.doctor_bridge import run_all_checks, format_report

            report = run_all_checks(categories=categories, fix=fix, quick=quick)

            if json_output:
                from dataclasses import asdict
                print(json.dumps(asdict(report), indent=2, default=str))
            else:
                print(format_report(report))

            return 0 if report.healthy else 1
        else:
            logger.warning("Health validators not found at %s, running basic checks", health_dir)

    except ImportError as e:
        logger.warning("Doctor bridge not available (%s), running basic checks", e)
    except Exception as e:
        logger.error("Health check error: %s", e)

    # Fallback: basic path and import checks
    return _basic_health_check(fix=fix)


def _basic_health_check(fix: bool = False) -> int:
    """Minimal health check when doctor_bridge is unavailable."""
    issues = 0

    try:
        from paths import resolver
        print(f"  ✓ PathResolver: root={resolver.root}, docker={resolver.is_docker}")
    except ImportError as e:
        print(f"  ✗ PathResolver import failed: {e}")
        issues += 1

    try:
        from gateway.protocol import GatewayMessage
        print("  ✓ Gateway protocol importable")
    except ImportError as e:
        print(f"  ✗ Gateway protocol import failed: {e}")
        issues += 1

    try:
        from hermes_constants import get_hermes_home
        home = get_hermes_home()
        print(f"  ✓ Hermes home: {home}")
    except ImportError as e:
        print(f"  ✗ Hermes constants import failed: {e}")
        issues += 1

    if fix:
        try:
            from paths import resolver
            resolver.ensure_dirs()
            print("  ✓ Ensured all directories exist")
        except Exception as e:
            print(f"  ✗ Could not ensure directories: {e}")
            issues += 1

    return 1 if issues > 0 else 0


def run_noninteractive_setup(hermes_home: Path = None) -> int:
    """Non-interactive setup: inject keys from OpenClaw config or environment.

    Used by OpenClaw's `openclaw onboard` to silently configure Hermes
    without requiring user interaction.
    """
    if hermes_home is None:
        try:
            from paths import resolver
            hermes_home = resolver.hermes_home
        except ImportError:
            hermes_home = Path(os.getenv("HERMES_HOME", "/runtime"))

    logger.info("Running non-interactive setup for %s", hermes_home)

    # 1. Ensure directories
    try:
        from paths import resolver
        resolver.ensure_dirs()
        logger.info("Ensured all PathResolver directories exist")
    except ImportError:
        for subdir in ["sessions", "memory", "logs", "state", "checkpoints",
                        "skills", "tools", "cron", ".secrets"]:
            (hermes_home / subdir).mkdir(parents=True, exist_ok=True)
        logger.info("Ensured basic directories under %s", hermes_home)

    # 2. Create identity stubs if missing
    for fname in ["SOUL.md", "USER.md", "AGENTS.md", "IDENTITY.md", "HEARTBEAT.md", "TOOLS.md"]:
        fpath = hermes_home / fname
        if not fpath.exists():
            try:
                fpath.write_text(f"# {fname.replace('.md', '')} — agent\n", encoding="utf-8")
                logger.info("Created %s", fpath)
            except PermissionError:
                logger.warning("Cannot create %s (permission denied)", fpath)

    # 3. Create config.yaml stub if missing
    config_path = hermes_home / "config.yaml"
    if not config_path.exists():
        try:
            config_path.write_text(
                "# Auto-generated by hermes runtime init\n"
                "model:\n"
                "  default: xiaomi/mimo-v2-pro\n"
                "  provider: nous\n"
                "  base_url: https://inference-api.nousresearch.com/v1\n"
                "\n"
                "tools:\n"
                "  profile: coding\n"
                "\n"
                "memory:\n"
                "  enabled: true\n"
                "  max_chars: 100000\n"
                "\n"
                "skills:\n"
                "  enabled: true\n",
                encoding="utf-8"
            )
            logger.info("Created config.yaml stub")
        except PermissionError:
            logger.warning("Cannot create config.yaml (permission denied)")

    # 4. Create agent.json stub if missing
    agent_json = hermes_home / "agent.json"
    if not agent_json.exists():
        try:
            agent_json.write_text(json.dumps({
                "builderCode": {
                    "code": "bc_default",
                    "hex": "0x62635f64656661756c74",
                    "owner": "0x0000000000000000000000000000000000000000",
                    "hardwired": True,
                    "enforced": True,
                }
            }, indent=2), encoding="utf-8")
            logger.info("Created agent.json stub")
        except PermissionError:
            logger.warning("Cannot create agent.json (permission denied)")

    # 5. Try key injection from OpenClaw config
    try:
        scripts_dir = Path(__file__).resolve().parent.parent.parent / "scripts"
        if (scripts_dir / "key_inject.py").exists():
            sys.path.insert(0, str(scripts_dir.parent))
            from scripts.key_inject import inject_keys, load_openclaw_config

            config = load_openclaw_config()
            if config:
                injected, skipped, messages = inject_keys(config, hermes_home)
                for msg in messages:
                    logger.info("Key inject: %s", msg)
                logger.info("Key injection: %d injected, %d skipped", injected, skipped)
            else:
                logger.info("No OpenClaw config found, skipping key injection")
        else:
            logger.debug("key_inject.py not found, skipping")
    except ImportError as e:
        logger.debug("Key injection not available: %s", e)
    except Exception as e:
        logger.warning("Key injection failed: %s", e)

    # 6. Load .env if present
    env_file = hermes_home / ".env"
    if env_file.exists():
        logger.info("Found .env at %s", env_file)
    else:
        logger.info("No .env found at %s (will be created by setup or key injection)", env_file)

    logger.info("Non-interactive setup complete for %s", hermes_home)
    return 0


def verify_runtime_environment():
    """Verify runtime environment is properly configured (original init logic)."""
    try:
        from paths import resolver
        hermes_home = resolver.hermes_home
    except ImportError:
        from hermes_constants import get_hermes_home
        hermes_home = get_hermes_home()

    required_dirs = [
        hermes_home / 'sessions',
        hermes_home / 'memory',
        hermes_home / 'logs',
        hermes_home / 'state',
        hermes_home / 'checkpoints',
    ]

    try:
        from paths import resolver
        required_dirs.append(resolver.agents_dir)
    except ImportError:
        required_dirs.append(Path('/agents'))

    logger.info("Verifying runtime environment: HERMES_HOME=%s", hermes_home)

    for directory in required_dirs:
        try:
            directory.mkdir(parents=True, exist_ok=True)
            logger.info("✓ Directory: %s", directory)
        except PermissionError:
            logger.warning("✗ Cannot create directory (permission denied): %s", directory)

    return hermes_home


def start_runtime():
    """Start the Hermes runtime daemon (original init logic)."""
    logger.info("=" * 60)
    logger.info("HERMES RUNTIME INITIALIZATION")
    logger.info("=" * 60)

    hermes_home = verify_runtime_environment()

    # Run pre-flight health check (quick)
    exit_code = run_health_checks(quick=True, fix=True)
    if exit_code != 0:
        logger.warning("Health check reported issues (exit=%d), continuing anyway", exit_code)

    # Try key injection from environment
    run_noninteractive_setup(hermes_home)

    # Start the daemon
    logger.info("=" * 60)
    logger.info("Starting Runtime Daemon...")
    logger.info("=" * 60)

    try:
        from runtime.daemon_manager import RuntimeDaemon
        daemon = RuntimeDaemon(hermes_home=hermes_home)

        for sig in (signal.SIGTERM, signal.SIGINT):
            asyncio.get_event_loop().add_signal_handler(
                sig,
                lambda: asyncio.create_task(daemon.stop())
            )

        try:
            asyncio.run(daemon.start())
        except KeyboardInterrupt:
            logger.info("Runtime interrupted by user")
            asyncio.run(daemon.stop())
        except Exception as e:
            logger.error("Runtime error: %s", e)
            raise

    except ImportError as e:
        logger.error("Cannot import RuntimeDaemon: %s", e)
        logger.info("Running in standalone mode — starting gateway directly")

        try:
            from gateway.run import start_gateway
            asyncio.run(start_gateway())
        except ImportError:
            logger.error("Cannot import gateway. Exiting.")
            sys.exit(1)
        except KeyboardInterrupt:
            logger.info("Gateway stopped by user")


def main():
    """CLI entry point with argument handling."""
    parser = argparse.ArgumentParser(description="Hermes Runtime Initialization")
    parser.add_argument("--doctor", action="store_true",
                       help="Run health checks and exit")
    parser.add_argument("--fix", action="store_true",
                       help="Auto-fix issues during health checks")
    parser.add_argument("--setup", action="store_true",
                       help="Run non-interactive setup (key injection, directory creation)")
    parser.add_argument("--quick", action="store_true",
                       help="Quick health check (paths, env, imports only)")
    parser.add_argument("--json", action="store_true",
                       help="Output health check results as JSON")
    parser.add_argument("--categories", nargs="+",
                       help="Specific health check categories to run")
    parser.add_argument("--verbose", "-v", action="store_true",
                       help="Verbose output")

    args = parser.parse_args()

    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=log_level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    if args.doctor:
        exit_code = run_health_checks(
            quick=args.quick,
            fix=args.fix,
            categories=args.categories,
            json_output=args.json,
        )
        sys.exit(exit_code)

    if args.setup:
        exit_code = run_noninteractive_setup()
        sys.exit(exit_code)

    # Default: start the runtime
    start_runtime()


if __name__ == '__main__':
    main()